<?php

/**
 * This is a demonstration of a class
 * generated by a scaffold 
 * The command used was:
 * > oil generate scaffold country name:string iso_code:string
 */
class Controller_Country extends Controller_Template {

    public function before() {
	parent::before();
	if (Auth::has_access('country.read') == false) {
	    Session::set_flash("error", "List of countries is very secret!");
	    Response::redirect("/") and die();
	}
    }

    public function action_index() {
	$data['countries'] = Model_Country::find('all');
	$this->template->title = "Countries";
	$this->template->content = View::forge('country/index', $data);
    }

    public function action_view($id = null) {
	$data['country'] = Model_Country::find($id);

	is_null($id) and Response::redirect('Country');

	$this->template->title = "Country";
	$this->template->content = View::forge('country/view', $data);
    }

    public function action_create() {
	if (Auth::has_access('country.create') == false) {
	    Session::set_flash("error", "Only admins may add countries!");
	    Response::redirect("country/") and die();
	}

	if (Input::method() == 'POST') {
	    $val = Model_Country::validate('create');

	    if ($val->run()) {
		$country = Model_Country::forge(array(
			    'name' => Input::post('name'),
			    'iso_code' => Input::post('iso_code'),
			));

		if ($country and $country->save()) {
		    Session::set_flash('success', 'Added country #' . $country->id . '.');

		    Response::redirect('country');
		} else {
		    Session::set_flash('error', 'Could not save country.');
		}
	    } else {
		Session::set_flash('error', $val->error());
	    }
	}

	$this->template->title = "Countries";
	$this->template->content = View::forge('country/create');
    }

    public function action_edit($id = null) {
	if (Auth::has_access('country.edit') == false) {
	    Session::set_flash("error", "Only admins may edit countries!");
	    Response::redirect("country/") and die();
	}

	is_null($id) and Response::redirect('Country');

	$country = Model_Country::find($id);

	$val = Model_Country::validate('edit');

	if ($val->run()) {
	    $country->name = Input::post('name');
	    $country->iso_code = Input::post('iso_code');

	    if ($country->save()) {
		Session::set_flash('success', 'Updated country #' . $id);

		Response::redirect('country');
	    } else {
		Session::set_flash('error', 'Could not update country #' . $id);
	    }
	} else {
	    if (Input::method() == 'POST') {
		$country->name = $val->validated('name');
		$country->iso_code = $val->validated('iso_code');

		Session::set_flash('error', $val->error());
	    }

	    $this->template->set_global('country', $country, false);
	}

	$this->template->title = "Countries";
	$this->template->content = View::forge('country/edit');
    }

    public function action_delete($id = null) {
	if (Auth::has_access('country.delete') == false) {
	    Session::set_flash("error", "Only admins may delete countries!");
	    Response::redirect("country/") and die();
	}

	if ($country = Model_Country::find($id)) {
	    $country->delete();

	    Session::set_flash('success', 'Deleted country #' . $id);
	} else {
	    Session::set_flash('error', 'Could not delete country #' . $id);
	}

	Response::redirect('country');
    }

}