<?php
/* This controller and its actions was generated by
 * an "oil generate" command. 
 * 
 * > oil generate controller location index create view delete 
 * 
 * The default action implementations are very simple.
 */
class Controller_Location extends Controller_Public
{

	public function action_index()
	{
		$this->template->title = 'Location &raquo; Index';
		$this->template->content = View::forge('location/index');
	}

	public function action_create()
	{
	    //assumption: this will only be called using ajax
	    if (!Input::is_ajax()){
		return Response::forge("Access forbidden, only AJAX calls allowed",403);
	    }
	    
	    if ( ! Auth::has_access("location.create")) {
		return Response::forge("Only admins allowed here",403);
	    }
	    
	    if (Input::post("location_title", null)!=null) {
		  $loc = Model_Orm_Location::forge();
		  $loc->title = Input::post("location_title");
		  $loc->save();
		  $ret = array("id"=>$loc->id);
		  return Response::forge(
			    Format::forge()->to_json($ret),
			    200, 
			    array("Content-Type"=>"application/json"));
    	    }
	}

	public function action_view()
	{
		$this->template->title = 'Location &raquo; View';
		$this->template->content = View::forge('location/view');
	}

	public function action_delete()
	{
		$this->template->title = 'Location &raquo; Delete';
		$this->template->content = View::forge('location/delete');
	}
	
	public function action_search($term=null){
	    if ($term==null) {
		$term = Input::get("term");
	    }
	    //only ajax requests served here 
	    //(! Input::is_ajax()) and Response::redirect("location");
	    $clean_query =  Security::clean($term);
	    $data["locations"] = array();
	    if ($clean_query != "") {
		$data["locations"] = Model_Orm_Location::query()
					->where("title", "like", $clean_query."%")
					->get();
	    }
	    
	    $response = Response::forge(View::forge("location/search", $data));
	    $response->set_header("Content-Type","application/json");
	    return $response;
	}

}
