<?php
/* This controller and its actions was generated by
 * an "oil generate" command. 
 * 
 * > oil generate controller location index create view delete 
 * 
 * The default action implementations are very simple.
 */
class Controller_Location extends Controller_Template
{

	public function action_index()
	{
		$this->template->title = 'Location &raquo; Index';
		$this->template->content = View::forge('location/index');
	}

	public function action_create()
	{
		$this->template->title = 'Location &raquo; Create';
		$this->template->content = View::forge('location/create');
	}

	public function action_view()
	{
		$this->template->title = 'Location &raquo; View';
		$this->template->content = View::forge('location/view');
	}

	public function action_delete()
	{
		$this->template->title = 'Location &raquo; Delete';
		$this->template->content = View::forge('location/delete');
	}

}
